Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -28,7 +28,7 @@ permissions:
   contents: read
 
 jobs:
-  snyk:
+   snyk:
     permissions:
       contents: read # for actions/checkout to fetch code
       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
@@ -37,33 +37,43 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Set up Snyk CLI to check for security issues
+      - uses: actions/setup-node@v4
+        with:
+           node-version: 20
+      - uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Snyk Code test
+        run: snyk code test --sarif > snyk-code.sarif  || true
+      - name: Snyk Open Source monitor
+        run: snyk monitor --all-projects
+
+        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+        # Use || true to not fail the pipeline.
+      - name: Snyk IaC test and report
+        run: snyk iac test --report  || true
+      - name: Upload result to GitHub Code Scanning
+        uses: pixee/upload-tool-results-action@v2.4.0
+        with:
+          tool: snyk
+          file: snyk-code.sarif
         # Snyk can be used to break the build when it detects security issues.
         # In this case we want to upload the SAST issues to GitHub Code Scanning
         
 
         # For Snyk Open Source you must first set up the development environment for your application's dependencies
         # For example for Node
-      - uses: actions/setup-node@v4
-        with:
-           node-version: 20
-      - uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
-        env:
+  
+
           # This is where you will need to introduce the Snyk API token created with your Snyk account
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
 
         # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
         # Use || true to not fail the pipeline
-    - name: Snyk Code test
-      run: snyk code test --sarif > snyk-code.sarif  || true
+    
 
         # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-     - name: Snyk Open Source monitor
-       run: snyk monitor --all-projects
-
-        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
-        # Use || true to not fail the pipeline.
-     - name: Snyk IaC test and report
-       run: snyk iac test --report  || true
+     
 
         # Build the docker image for testing
       
@@ -71,8 +81,4 @@ jobs:
 
 
         # Push the Snyk Code results into GitHub Code Scanning tab
-    - name: Upload result to GitHub Code Scanning
-      uses: pixee/upload-tool-results-action@v2.4.0
-      with:
-          tool: snyk
-          file: snyk-code.sarif
+
